// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url:
      !process.env["DATABASE_URL"] || process.env["DATABASE_URL"].includes("johndoe")
        ? "postgresql://calendar_user:calendar_password@localhost:5432/calendar_app?schema=public"
        : process.env["DATABASE_URL"],
  },
});
